/*export const tipo_material = [
  {
    "id": 1,
    "id_tipo": 1,
    "id_padre": null,
    "nombre": "COMPENDIO",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 2,
    "id_tipo": 1,
    "id_padre": null,
    "nombre": "HELICODIAPOSITIVA",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/13/200/100"
  },
  {
    "id": 3,
    "id_tipo": 1,
    "id_padre": null,
    "nombre": "BALOTARIO",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/33/200/100"
  },
  {
    "id": 4,
    "id_tipo": 1,
    "id_padre": null,
    "nombre": "SOLUCIONARIO DE BALOTARIO",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/43/200/100"
  },
  {
    "id": 3146,
    "id_tipo": 2,
    "id_padre": [1, 2],
    "nombre": "TOMO 1",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3147,
    "id_tipo": 2,
    "id_padre": [1, 2],
    "nombre": "TOMO 2",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3164,
    "id_tipo": 2,
    "id_padre": [1, 2],
    "nombre": "TOMO 3",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3165,
    "id_tipo": 2,
    "id_padre": [1, 2],
    "nombre": "TOMO 4",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3166,
    "id_tipo": 2,
    "id_padre": [1, 2],
    "nombre": "TOMO 5",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3167,
    "id_tipo": 2,
    "id_padre": [1, 2],
    "nombre": "TOMO 6",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3168,
    "id_tipo": 2,
    "id_padre": [1, 2],
    "nombre": "TOMO 7",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3169,
    "id_tipo": 2,
    "id_padre": [1, 2],
    "nombre": "TOMO 8",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3170,
    "id_tipo": 2,
    "id_padre": [3, 4],
    "nombre": "MENSUAL 1",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100",
  },
  {
    "id": 3171,
    "id_tipo": 2,
    "id_padre": [3, 4],
    "nombre": "MENSUAL 2",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100",
  },
  {
    "id": 3172,
    "id_tipo": 2,
    "id_padre": [3, 4],
    "nombre": "MENSUAL 3",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100",
  },
  {
    "id": 3173,
    "id_tipo": 2,
    "id_padre": [3, 4],
    "nombre": "MENSUAL 4",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100",
  },
  {
    "id": 3174,
    "id_tipo": 2,
    "id_padre": [3, 4],
    "nombre": "BIMESTRAL 1",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100",
  },
  {
    "id": 3175,
    "id_tipo": 2,
    "id_padre": [3, 4],
    "nombre": "BIMESTRAL 2",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100",
  },
  {
    "id": 3176,
    "id_tipo": 2,
    "id_padre": [3, 4],
    "nombre": "BIMESTRAL 3",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100",
  },
  {
    "id": 3177,
    "id_tipo": 2,
    "id_padre": [3, 4],
    "nombre": "BIMESTRAL 4",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100",
  },
  {
    "id": 3196,
    "id_tipo": 3,
    "id_padre": [3146, 3147, 3164, 3165, 3166, 3167, 3168, 3169],
    "nombre": "CAPÍTULO 1",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3197,
    "id_tipo": 3,
    "id_padre": [3146, 3147, 3164, 3165, 3166, 3167, 3168, 3169],
    "nombre": "CAPÍTULO 2",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3198,
    "id_tipo": 3,
    "id_padre": [3146, 3147, 3164, 3165, 3166, 3167, 3168, 3169],
    "nombre": "CAPÍTULO 3",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3199,
    "id_tipo": 3,
    "id_padre": [3146, 3147, 3164, 3165, 3166, 3167, 3168, 3169],
    "nombre": "ASESORÍA",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3200,
    "id_tipo": 3,
    "id_padre": [3146, 3147, 3164, 3165, 3166, 3167, 3168, 3169],
    "nombre": "REFORZAMIENTO",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  }
];*/

export const tipo_material = [
  {
    "id": 2,
    "id_tipo": 1,
    "id_padre": null,
    "nombre": "HELICODIAPOSITIVA",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/13/200/100"
  },
  {
    "id": 5,
    "id_tipo": 1,
    "id_padre": null,
    "nombre": "BOLETINES",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/13/200/100"
  },
  {
    "id": 3146,
    "id_tipo": 2,
    "id_padre": [2, 5],
    "nombre": "INTRODUCTORIO",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3217,
    "id_tipo": 2,
    "id_padre": [2, 5],
    "nombre": "SEMANA 1",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3218,
    "id_tipo": 2,
    "id_padre": [2, 5],
    "nombre": "SEMANA 2",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3219,
    "id_tipo": 2,
    "id_padre": [2, 5],
    "nombre": "SEMANA 3",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3220,
    "id_tipo": 2,
    "id_padre": [2, 5],
    "nombre": "SEMANA 4",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3221,
    "id_tipo": 2,
    "id_padre": [2, 5],
    "nombre": "SEMANA 5",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 3222,
    "id_tipo": 2,
    "id_padre": [2, 5],
    "nombre": "SEMANA 6",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 6,
    "id_tipo": 3,
    "id_padre": [3146, 3217, 3218, 3219, 3220, 3221, 3222],
    "nombre": "SESIÓN",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
  {
    "id": 7,
    "id_tipo": 3,
    "id_padre": [3146, 3217, 3218, 3219, 3220, 3221, 3222],
    "nombre": "HELICOMOTIVACIÓN",
    "nivel": "Secundaria",
    "empresa": "Saco Oliveros",
    "empresa_logo": "https://trismegisto.sacooliveros.edu.pe/logo.jpg",
    "imagen": "https://picsum.photos/id/3/200/100"
  },
];